name: 'Notify Slack'
description: 'Send notifications to Slack channels'
author: 'zmihai'

inputs:
  webhook-url:
    description: 'Slack webhook URL'
    required: true
  message:
    description: 'Message to send'
    required: true
  status:
    description: 'Status (success, failure, warning)'
    required: false
    default: 'success'
  channel:
    description: 'Slack channel (overrides webhook default)'
    required: false
  mention-users:
    description: 'Comma-separated list of user IDs to mention'
    required: false

runs:
  using: 'composite'
  steps:
    - name: Determine color
      id: color
      shell: bash
      run: |
        case "${{ inputs.status }}" in
          success)
            echo "color=good" >> $GITHUB_OUTPUT
            echo "emoji=:white_check_mark:" >> $GITHUB_OUTPUT
            ;;
          failure)
            echo "color=danger" >> $GITHUB_OUTPUT
            echo "emoji=:x:" >> $GITHUB_OUTPUT
            ;;
          warning)
            echo "color=warning" >> $GITHUB_OUTPUT
            echo "emoji=:warning:" >> $GITHUB_OUTPUT
            ;;
          *)
            echo "color=#808080" >> $GITHUB_OUTPUT
            echo "emoji=:information_source:" >> $GITHUB_OUTPUT
            ;;
        esac
    
    - name: Send Slack notification
      shell: bash
      env:
        WEBHOOK_URL: ${{ inputs.webhook-url }}
      run: |
        MENTIONS=""
        if [ -n "${{ inputs.mention-users }}" ]; then
          IFS=',' read -ra USERS <<< "${{ inputs.mention-users }}"
          for user in "${USERS[@]}"; do
            MENTIONS="${MENTIONS}<@${user}> "
          done
        fi
        
        PAYLOAD=$(cat <<EOF
        {
          "channel": "${{ inputs.channel }}",
          "attachments": [
            {
              "color": "${{ steps.color.outputs.color }}",
              "text": "${{ steps.color.outputs.emoji }} ${{ inputs.message }}\n${MENTIONS}",
              "footer": "GitHub Actions",
              "footer_icon": "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png",
              "ts": $(date +%s)
            }
          ]
        }
        EOF
        )
        
        curl -X POST -H 'Content-type: application/json' \
          --data "$PAYLOAD" \
          "$WEBHOOK_URL"

branding:
  icon: 'message-circle'
  color: 'purple'
