name: CI

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  ci:
    uses: zmihai/.github/.github/workflows/reusable-ci-npm.yml@v0.2.0
    with:
      node-version: '20'
      run-lint: true
      run-test: true
      run-build: true
      build-before-test: false
