name: Release

on:
  workflow_dispatch:
    inputs:
      release-type:
        description: 'Release type'
        required: true
        type: choice
        options:
          - patch
          - minor
          - major
        default: 'patch'

jobs:
  release:
    uses: zmihai/.github/.github/workflows/reusable-release.yml@master
    with:
      release-type: ${{ inputs.release-type }}
      node-version: '20'
      create-github-release: true
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
