name: Security Scan

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    # Run every day at 2 AM UTC
    - cron: '0 2 * * *'

jobs:
  security:
    uses: zmihai/.github/.github/workflows/reusable-security-scan.yml@v0.1.0
    with:
      scan-dependencies: true
      scan-code: true
      language: 'javascript'
